"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KeyOnlyDirectives = exports.CspDirectiveKeys = exports.CspKeywords = void 0;
var CspKeywords;
(function (CspKeywords) {
    CspKeywords[CspKeywords["'none'"] = 0] = "'none'";
    CspKeywords[CspKeywords["'report-sample'"] = 1] = "'report-sample'";
    CspKeywords[CspKeywords["'self'"] = 2] = "'self'";
    CspKeywords[CspKeywords["'strict-dynamic'"] = 3] = "'strict-dynamic'";
    CspKeywords[CspKeywords["'unsafe-allow-redirects'"] = 4] = "'unsafe-allow-redirects'";
    CspKeywords[CspKeywords["'unsafe-eval'"] = 5] = "'unsafe-eval'";
    CspKeywords[CspKeywords["'unsafe-hashes'"] = 6] = "'unsafe-hashes'";
    CspKeywords[CspKeywords["'unsafe-inline'"] = 7] = "'unsafe-inline'";
    CspKeywords[CspKeywords["data:"] = 8] = "data:";
})(CspKeywords = exports.CspKeywords || (exports.CspKeywords = {}));
var CspDirectiveKeys;
(function (CspDirectiveKeys) {
    CspDirectiveKeys[CspDirectiveKeys["base-uri"] = 0] = "base-uri";
    CspDirectiveKeys[CspDirectiveKeys["block-all-mixed-content"] = 1] = "block-all-mixed-content";
    CspDirectiveKeys[CspDirectiveKeys["connect-src"] = 2] = "connect-src";
    CspDirectiveKeys[CspDirectiveKeys["default-src"] = 3] = "default-src";
    CspDirectiveKeys[CspDirectiveKeys["font-src"] = 4] = "font-src";
    CspDirectiveKeys[CspDirectiveKeys["form-action"] = 5] = "form-action";
    CspDirectiveKeys[CspDirectiveKeys["frame-ancestors"] = 6] = "frame-ancestors";
    CspDirectiveKeys[CspDirectiveKeys["frame-src"] = 7] = "frame-src";
    CspDirectiveKeys[CspDirectiveKeys["img-src"] = 8] = "img-src";
    CspDirectiveKeys[CspDirectiveKeys["manifest-src"] = 9] = "manifest-src";
    CspDirectiveKeys[CspDirectiveKeys["media-src"] = 10] = "media-src";
    CspDirectiveKeys[CspDirectiveKeys["navigate-to"] = 11] = "navigate-to";
    CspDirectiveKeys[CspDirectiveKeys["object-src"] = 12] = "object-src";
    CspDirectiveKeys[CspDirectiveKeys["plugin-types"] = 13] = "plugin-types";
    CspDirectiveKeys[CspDirectiveKeys["prefetch-src"] = 14] = "prefetch-src";
    CspDirectiveKeys[CspDirectiveKeys["report-to"] = 15] = "report-to";
    CspDirectiveKeys[CspDirectiveKeys["report-uri"] = 16] = "report-uri";
    CspDirectiveKeys[CspDirectiveKeys["require-sri-for"] = 17] = "require-sri-for";
    CspDirectiveKeys[CspDirectiveKeys["require-trusted-types-for"] = 18] = "require-trusted-types-for";
    CspDirectiveKeys[CspDirectiveKeys["sandbox"] = 19] = "sandbox";
    CspDirectiveKeys[CspDirectiveKeys["script-src-attr"] = 20] = "script-src-attr";
    CspDirectiveKeys[CspDirectiveKeys["script-src-elem"] = 21] = "script-src-elem";
    CspDirectiveKeys[CspDirectiveKeys["script-src"] = 22] = "script-src";
    CspDirectiveKeys[CspDirectiveKeys["style-src-attr"] = 23] = "style-src-attr";
    CspDirectiveKeys[CspDirectiveKeys["style-src-elem"] = 24] = "style-src-elem";
    CspDirectiveKeys[CspDirectiveKeys["style-src"] = 25] = "style-src";
    CspDirectiveKeys[CspDirectiveKeys["trusted-types"] = 26] = "trusted-types";
    CspDirectiveKeys[CspDirectiveKeys["upgrade-insecure-requests"] = 27] = "upgrade-insecure-requests";
    CspDirectiveKeys[CspDirectiveKeys["worker-src"] = 28] = "worker-src";
})(CspDirectiveKeys = exports.CspDirectiveKeys || (exports.CspDirectiveKeys = {}));
var KeyOnlyDirectives;
(function (KeyOnlyDirectives) {
    KeyOnlyDirectives[KeyOnlyDirectives["block-all-mixed-content"] = 0] = "block-all-mixed-content";
    KeyOnlyDirectives[KeyOnlyDirectives["upgrade-insecure-requests"] = 1] = "upgrade-insecure-requests";
})(KeyOnlyDirectives = exports.KeyOnlyDirectives || (exports.KeyOnlyDirectives = {}));
