enum CspKeywords {
  "'none'",
  "'report-sample'",
  "'self'",
  "'strict-dynamic'",
  "'unsafe-allow-redirects'",
  "'unsafe-eval'",
  "'unsafe-hashes'",
  "'unsafe-inline'",
  "data:",
}

enum CspDirectiveKeys {
  "base-uri",
  "block-all-mixed-content",
  "connect-src",
  "default-src",
  "font-src",
  "form-action",
  "frame-ancestors",
  "frame-src",
  "img-src",
  "manifest-src",
  "media-src",
  "navigate-to",
  "object-src",
  "plugin-types",
  "prefetch-src",
  "report-to",
  "report-uri",
  "require-sri-for",
  "require-trusted-types-for",
  "sandbox",
  "script-src-attr",
  "script-src-elem",
  "script-src",
  "style-src-attr",
  "style-src-elem",
  "style-src",
  "trusted-types",
  "upgrade-insecure-requests",
  "worker-src",
}

enum KeyOnlyDirectives {
  "block-all-mixed-content",
  "upgrade-insecure-requests",
}
